### ISSUE TITLE
Will there be singleplayer mode?

### ISSUE THREAD

**Issue by wetstreet** [Technoguyfication/Minecraft-Unity3D#5]
Just curious.

**Comment by wetstreet** [comment]
I tried to play this game with my Mojang account but failed, stuck at loading scene stage, dunno why, no error. I think a singleplayer option will improve the experience for people who just want to try it out without having to login and connect to a server etc.

**Comment by michaelsakharov** [comment]
I cant imagine so, Single player is MUCH harder to achieve, since right now the server does all the work, so actual game play is not required.

But you can already do single player just like normal minecraft by running a server in the background. Minecraft already does this, this is how LAN works, its just theirs is invisible.

**Comment by wetstreet** [comment]
I get what you said. Adding single player mode needs a lot of work, but it gives you integrity, which means you don't have to depend on any other program to run. I think it's one of the essentials if you even wanna extend this to be a full game and add your own stuff to make this a new game.

But it's just different purposes, a client without server embeded is totally fine. I'm just giving a suggestion or asking a question to know what the plan is.

**Comment by michaelsakharov** [comment]
I'm not the Dev, And I dont THINK the dev wants to make a game, its supposed to be just a Minecraft Client I think.

**Comment by wetstreet** [comment]
Okay
